name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: >
        sudo apt install -y \
          gnuplot \
          inkscape \
          ipe \
          pdftk \
          texlive
    - name: texhash
      run: |
        mkdir -p ~/texmf/tex/latex/ods/
        ln -s $PWD/latex/ods-colors.sty ~/texmf/tex/latex/ods/
        texhash
    - name: make
      run: make
