name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt install -y \
          gnuplot \
          inkscape \
          ipe \
          latex2html \
          pdftk \
          python2 \
          texlive-full
    - name: texhash
      run: |
        mkdir -p ~/texmf/tex/latex/ods/
        ln -s $PWD/latex/ods-colors.sty ~/texmf/tex/latex/ods/
        texhash
    - name: build
      run: |
        make
        # make -C latex html
        make tarballs
    - name: upload pdfs
      uses: actions/upload-artifact@v4.3.0
      with:
        path: latex/*.pdf
        if-no-files-found: error
    - name: upload tarballs
      uses: actions/upload-artifact@v4.3.0
      with:
        path: ./*.tgz
        if-no-files-found: error
