name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.3.1
      with:
        packages: gnuplot inkscape ipe pdftk python2 texlive-full
        version: 1.1.0
    - name: override python
      run: |
        which python
        which python2
        which python3
    - name: texhash
      run: |
        mkdir -p ~/texmf/tex/latex/ods/
        ln -s $PWD/latex/ods-colors.sty ~/texmf/tex/latex/ods/
        texhash
    - name: make
      run: make
