name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: >
        sudo apt install -y \
          gnuplot \
          inkscape \
          ipe \
          pdftk \
          python2 \
          texlive-full
        texhash
    - name: make
      run: make
