name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-pdfs:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
    - name: install dependencies
      run: |
        sudo apt install -y \
          gnuplot \
          inkscape \
          ipe \
          latex2html \
          pdftk \
          python2 \
          texlive-full
    - name: texhash
      run: |
        mkdir -p ~/texmf/tex/latex/ods/
        ln -s $PWD/latex/ods-colors.sty ~/texmf/tex/latex/ods/
        texhash
    - name: build and publish
      run: make
    - name: upload pdfs
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ods-pdfs
        path: latex/*.pdf
        if-no-files-found: error
  build-html:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
    - name: install dependencies
      run: |
        sudo apt install -y \
          gnuplot \
          inkscape \
          ipe \
          latex2html \
          pdftk \
          python2 \
          texlive-full
    - name: texhash
      run: |
        mkdir -p ~/texmf/tex/latex/ods/
        ln -s $PWD/latex/ods-colors.sty ~/texmf/tex/latex/ods/
        texhash
    - name: build and publish
      run: |
        make -C latex images
        make -C latex html
    - name: upload cpp html
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ods-cpp-html
        path: latex/ods-cpp
        if-no-files-found: error
    - name: upload java html
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ods-java-html
        path: latex/ods-java
        if-no-files-found: error
    - name: upload python html
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ods-python-html
        path: latex/ods-python
        if-no-files-found: error
  build-tarballs:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
    - name: install dependencies
      run: |
        sudo apt install -y \
          gnuplot \
          inkscape \
          ipe \
          latex2html \
          pdftk \
          python2 \
          texlive-full
    - name: texhash
      run: |
        mkdir -p ~/texmf/tex/latex/ods/
        ln -s $PWD/latex/ods-colors.sty ~/texmf/tex/latex/ods/
        texhash
    - name: build and publish
      run: make tarballs
    - name: upload tarballs
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ods-tarballs
        path: ./*.tgz
        if-no-files-found: error
