name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install cacheable dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.3.1
      with:
        packages: gnuplot ipe pdftk python2 texlive-full
        version: 1.2.0
        execute_install_scripts: true
    - name: install non-cacheable dependencies
      run: sudo apt install -y inkscape
    - name: override python
      run: |
        which $(which python2) $(which python)
    - name: texhash
      run: |
        mkdir -p ~/texmf/tex/latex/ods/
        ln -s $PWD/latex/ods-colors.sty ~/texmf/tex/latex/ods/
        texhash
    - name: build
      run: make
